services:
  Dbp\Relay\CoreConnectorOidcBundle\Authenticator\BearerAuthenticator:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreConnectorOidcBundle\Authenticator\BearerUserProvider:
    autowire: true
    autoconfigure: true
    calls:
      - setCache: [ '@dbp.relay.auth.cache.user_roles' ]

  Dbp\Relay\CoreConnectorOidcBundle\UserSession\OIDCUserSessionProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreConnectorOidcBundle\UserSession\OIDCUserSessionProviderInterface:
    '@Dbp\Relay\CoreConnectorOidcBundle\UserSession\OIDCUserSessionProvider'

  Dbp\Relay\CoreConnectorOidcBundle\OIDCProvider\OIDProvider:
    autowire: true
    autoconfigure: true
    calls:
      - setCache: [ '@dbp.relay.auth.cache.oid_provider' ]

  Dbp\Relay\CoreConnectorOidcBundle\Authenticator\BearerUserProviderInterface:
    '@Dbp\Relay\CoreConnectorOidcBundle\Authenticator\BearerUserProvider'

  Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface:
    '@Dbp\Relay\CoreConnectorOidcBundle\Authenticator\BearerAuthenticator'

  Dbp\Relay\CoreConnectorOidcBundle\Service\DefaultUserRoles:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreConnectorOidcBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CoreConnectorOidcBundle\API\UserRolesInterface:
    '@Dbp\Relay\CoreConnectorOidcBundle\Service\DefaultUserRoles'

  Dbp\Relay\CoreConnectorOidcBundle\Service\AuthorizationDataProvider:
    autowire: true
    autoconfigure: true

  dbp.relay.auth.cache.oid_provider:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 60 }

  dbp.relay.auth.cache.user_roles:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 60 }
